services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=capim
    volumes:
      - "./capim:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - airflow  
      - postgres-compose-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "7070:80"
    depends_on:
      - pgdatabase      
    networks:
      - postgres-compose-network

networks:
  airflow:
    external:
      name: airflow_default
  postgres-compose-network:
    driver: bridge
